/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2021-10-14

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32f10x.h"
#include "stm32f10x_conf.h"

/* Private typedef */
/* Private define  */
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */
/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
void my_delay(unsigned int count)
{
while(count>0)
{
count--; }
}
int main(void)
{
  int i = 0;// Define variable type GPIO
  GPIO_InitTypeDef GPIO_InitStruct_num;
  RCC_DeInit();
  int count = 0;
  int status = 1;
  RCC_HSEConfig(RCC_HSE_ON);
  RCC_PLLConfig(RCC_PLLSource_HSE_Div1, RCC_PLLMul_9); // PLL ใช้ HSE แบบไม่หารและคูณ 9 เท่า
  RCC_PLLCmd(ENABLE);//เปิดใช้งาน PLL
  RCC_SYSCLKConfig(RCC_SYSCLKSource_PLLCLK); //ให้ SYSCLK =สัญญาณนาฬิกาที่ออกจาก PLL
  RCC_HCLKConfig(RCC_SYSCLK_Div1);//.ให้ HCLK (AHB) = SYSCLK
  RCC_PCLK1Config(RCC_HCLK_Div2);//.ให้ PCLK1 (APB1) = HCLK/2
  RCC_PCLK2Config(RCC_HCLK_Div1);//.ให้ PCLK2 (APB2) = HCLK
  RCC_AHBPeriphClockCmd(RCC_AHBPeriph_DMA1, ENABLE);//72MHZ
  RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB, ENABLE);
  RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO, ENABLE);
  GPIO_PinRemapConfig(GPIO_Remap_SWJ_JTAGDisable, ENABLE);
  GPIO_InitStruct_num.GPIO_Pin= GPIO_Pin_0|GPIO_Pin_1|GPIO_Pin_3|GPIO_Pin_4|GPIO_Pin_8|GPIO_Pin_9|GPIO_Pin_10|GPIO_Pin_11|GPIO_Pin_12
  |GPIO_Pin_13|GPIO_Pin_14|GPIO_Pin_15;//use GPIOB 0,1,3,4,8,9,10,11,12,13,14,15
  GPIO_InitStruct_num.GPIO_Speed = GPIO_Speed_50MHz;//50Mhz
  GPIO_InitStruct_num.GPIO_Mode = GPIO_Mode_Out_PP;// Configure PA as push-pull output
  GPIO_Init(GPIOB, &GPIO_InitStruct_num);
  GPIO_Write(GPIOB, 0x001B);
  GPIO_ResetBits(GPIOB, GPIO_Pin_0|GPIO_Pin_1|GPIO_Pin_3|GPIO_Pin_4);// on digit 1-4
  GPIO_WriteBit(GPIOB, GPIO_Pin_8|GPIO_Pin_9|GPIO_Pin_10, Bit_SET);//set to be 7
  my_delay(10000000);
  /* Infinite loop */
  while (1)
  {
  
  GPIO_Write(GPIOB, 0x001B);//reset

  status = 200;
  while(status>0)//0 6 3 1
  {
  GPIO_Write(GPIOB, 0x3F19);//0
  my_delay(10000);
  GPIO_Write(GPIOB, 0x7D1A);//6
  my_delay(10000);
  GPIO_Write(GPIOB, 0x4F13);//3
  my_delay(10000);
  GPIO_Write(GPIOB, 0x060B);//1
  my_delay(10000);
  status--;
  }

  status = 200;
  while(status>0)//6 2 1 0
  {
  GPIO_Write(GPIOB, 0x7D19);//6
  my_delay(10000);
  GPIO_Write(GPIOB, 0x5B1A);//2
  my_delay(10000);
  GPIO_Write(GPIOB, 0x0613);//1
  my_delay(10000);
  GPIO_Write(GPIOB, 0x3F0B);//0
  my_delay(10000);
  status--; 
  }

  status = 200;
  while(status>0)// 5 9 4 0
  {
  GPIO_Write(GPIOB, 0x6D19);//5
  my_delay(10000);
  GPIO_Write(GPIOB, 0x6F1A);//9
  my_delay(10000);
  GPIO_Write(GPIOB, 0x6613);//4
  my_delay(10000);
  GPIO_Write(GPIOB, 0x3F0B);//0
  my_delay(10000);
  status--;
  }


  GPIO_Write(GPIOB, 0x4000);// - - - -
  my_delay(10000000);

 
  }
  }
  
